# Generated by Django 5.0.6 on 2024-07-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_pic1', models.ImageField(upload_to='product_pics/')),
                ('product_pic2', models.ImageField(blank=True, null=True, upload_to='product_pics/')),
                ('product_pic3', models.ImageField(blank=True, null=True, upload_to='product_pics/')),
                ('product_pic4', models.ImageField(blank=True, null=True, upload_to='product_pics/')),
                ('thumb', models.ImageField(upload_to='product_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
