# Generated by Django 5.0.7 on 2024-07-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='amount',
            new_name='money_amount',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
