# Generated by Django 5.0.7 on 2024-07-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_amount_withdrawal_money_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='is_processed',
            field=models.BooleanField(choices=[(True, 'Processed'), (False, 'Pending')], default=False),
        ),
    ]
