# Generated by Django 5.0.7 on 2024-07-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_withdrawal_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
