# Generated by Django 5.0.7 on 2024-07-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_withdrawal_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='is_processed',
            field=models.BooleanField(choices=[(True, 'Processed'), (False, 'Pending')], default=False),
        ),
    ]
